/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    obi: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshBasicMaterial;
  };
};

type ActionName = "obi_rotate";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Obi(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/obi.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions["obi_rotate"]) {
      actions["obi_rotate"].play();
    }
  });

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="obi"
          castShadow
          receiveShadow
          geometry={nodes.obi.geometry}
          material={materials["Material.004"]}
          rotation={[0, 0, -Math.PI / 6]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/obi.glb");
