/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ICO球: THREE.Mesh;
  };
  materials: {};
};

type ActionName = "ICO球Action.001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Core(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/core.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions["rotate"]) {
      actions["rotate"].play();
    }
    console.log(`\u001b[31m<Core> Rendered\u001b[0m`);
  });

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="ICO球"
          castShadow
          receiveShadow
          geometry={nodes.ICO球.geometry}
          material={nodes.ICO球.material}
          scale={1.5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/core.glb");
