/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    frame1: THREE.Mesh;
  };
  materials: {};
};

type ActionName = "frame_rotate";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Frame(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/frame.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions["frame_rotate"]) {
      actions["frame_rotate"].play();
    }
    console.log(`\u001b[31m<Frame> Rendered\u001b[0m`);
  });
  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="frame1"
          castShadow
          receiveShadow
          geometry={nodes.frame1.geometry}
          material={nodes.frame1.material}
          rotation={[Math.PI / 2, 0.436, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/frame.glb");
