/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh;
  };
  materials: {};
};

type ActionName = "globe_rotate";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Globe(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/globe.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions["globe_rotate"]) {
      actions["globe_rotate"].play();
    }
    console.log(`\u001b[31m<Globe> Rendered\u001b[0m`);
  });

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Curve"
          castShadow
          receiveShadow
          geometry={nodes.Curve.geometry}
          material={nodes.Curve.material}
          rotation={[0, 0, -0.454]}
          scale={[20, 1, 20]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/globe.glb");
