/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useAnimations } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    globe_outer: THREE.Mesh;
  };
  materials: {};
};

type ActionName = "globe_outer_rotate";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function GlobeOuter(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/globeOuter.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions["globe_outer_rotate"]) {
      actions["globe_outer_rotate"].play();
    }
    console.log(`\u001b[31m<GlobeOuter> Rendered\u001b[0m`);
  });
  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="globe_outer"
          castShadow
          receiveShadow
          geometry={nodes.globe_outer.geometry}
          material={nodes.globe_outer.material}
          rotation={[0, 0, -2.688]}
          scale={[2, 1, 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/globeOuter.glb");
